name: Extract ZIP File

on: [push]

permissions:
  contents: write  # Add this to allow the token to push

jobs:
  your-job:
    runs-on: ubuntu-latest
    steps:
      # ... your steps ...
      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
